[project]
name = "flask-playground"
version = "0.1.0"
dependencies = [
    "flask",
    "numpy",
    "python-dotenv",
    "flask-wtf",
    "flask-sqlalchemy",
    "flask-migrate",
    "flask-login",
    'email-validator',
    'aiosmtpd',
    'flask-moment',
    'flask-babel'
]

[tool.setuptools]
packages = ["app"]